import { spawnSync } from "node:child_process";
import { createAgentBranch } from "./github.js";
import { createLogger } from "../../utils/logger.js";

const log = createLogger("git-workflow");

// ─── Low-level helper ──────────────────────────────────

/**
 * Execute a git command synchronously.
 * Throws on non-zero exit code.
 */
function gitExec(cwd: string, args: string[]): { stdout: string; stderr: string } {
  const result = spawnSync("git", args, {
    cwd,
    stdio: "pipe",
    timeout: 30000,
    encoding: "utf-8",
  });

  // git binary not found
  if (result.error) {
    const code = (result.error as NodeJS.ErrnoException).code;
    if (code === "ENOENT") {
      throw new Error("git is not installed or not in PATH");
    }
    throw new Error(`git ${args[0]} spawn error: ${result.error.message}`);
  }

  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";

  if (result.status !== 0) {
    throw new Error(`git ${args[0]} failed: ${stderr.trim() || stdout.trim()}`);
  }

  return { stdout, stderr };
}

// ─── Public API ────────────────────────────────────────

/**
 * Stage all changes and create a commit.
 * Returns { committed: false } when there are no staged changes.
 */
export function commitTaskResult(
  workdir: string,
  taskTitle: string,
  agentName: string,
): { committed: boolean; filesChanged: number } {
  // Detect changes (use gitExec to catch .git missing / git not installed)
  const { stdout: statusOutput } = gitExec(workdir, ["status", "--porcelain"]);
  if (!statusOutput.trim()) {
    log.info("No changes to commit");
    return { committed: false, filesChanged: 0 };
  }

  const filesChanged = statusOutput.trim().split("\n").filter(Boolean).length;

  // Stage all changes
  gitExec(workdir, ["add", "-A"]);

  // Commit
  const message = `feat(nova-agent): ${taskTitle}\n\nAgent: ${agentName}\nGenerated by Nova Orbit`;
  gitExec(workdir, ["commit", "-m", message]);

  log.info(`Committed ${filesChanged} file(s): ${taskTitle}`);
  return { committed: true, filesChanged };
}

/**
 * Push the given branch to origin.
 * Returns false (logs only) on failure — never throws.
 */
export function pushBranch(workdir: string, branch: string): boolean {
  try {
    gitExec(workdir, ["push", "-u", "origin", branch]);
    log.info(`Pushed branch: ${branch}`);
    return true;
  } catch (err: any) {
    log.warn(`push failed: ${err.message}`);
    return false;
  }
}

/**
 * Create a pull request via the gh CLI.
 * Returns the PR URL on success, null on failure.
 */
export function createPR(
  workdir: string,
  branch: string,
  title: string,
  body: string,
): string | null {
  const result = spawnSync(
    "gh",
    ["pr", "create", "--head", branch, "--title", title, "--body", body],
    { cwd: workdir, stdio: "pipe", timeout: 30000, encoding: "utf-8" },
  );

  if (result.status === 0) {
    const url = result.stdout?.toString().trim();
    log.info(`PR created: ${url}`);
    return url || null;
  }

  log.warn(`gh pr create failed: ${result.stderr?.toString().trim()}`);
  return null;
}

// ─── High-level workflow ───────────────────────────────

export interface GitWorkflowResult {
  committed: boolean;
  pushed: boolean;
  prUrl: string | null;
  branch: string;
  filesChanged: number;
  error?: string;
}

export interface GitHubConfig {
  repoUrl: string;
  branch: string;
  autoPush: boolean;
  prMode: boolean;
}

export interface GitWorkflowOptions {
  /** worktree 모드에서 이미 생성된 branch 이름. 설정 시 createAgentBranch를 skip한다. */
  overrideBranch?: string;
}

/**
 * Execute the full git workflow after a task passes verification.
 *
 * Modes:
 *   prMode=true  → createAgentBranch → commit → push → PR
 *   autoPush=true → commit → push (on current/main branch)
 *   both false   → commit only (local)
 *
 * overrideBranch: worktree 모드에서 이미 branch가 생성된 경우 createAgentBranch를 skip한다.
 */
export function executeGitWorkflow(
  workdir: string,
  taskTitle: string,
  agentName: string,
  githubConfig: GitHubConfig,
  options: GitWorkflowOptions = {},
): GitWorkflowResult {
  const { autoPush, prMode, branch: baseBranch } = githubConfig;
  const { overrideBranch } = options;

  let activeBranch = baseBranch;
  let pushed = false;
  let prUrl: string | null = null;

  try {
    if (prMode) {
      // worktree 모드: branch가 이미 생성됨 — createAgentBranch skip
      if (overrideBranch) {
        activeBranch = overrideBranch;
      } else {
        // Create a dedicated agent branch
        activeBranch = createAgentBranch(workdir, agentName, taskTitle);
      }

      const commitResult = commitTaskResult(workdir, taskTitle, agentName);
      if (!commitResult.committed) {
        return { committed: false, pushed: false, prUrl: null, branch: activeBranch, filesChanged: 0 };
      }

      pushed = pushBranch(workdir, activeBranch);

      if (pushed) {
        const prBody = `Automated task implementation by Nova Orbit agent.\n\nTask: ${taskTitle}\nAgent: ${agentName}`;
        prUrl = createPR(workdir, activeBranch, taskTitle, prBody);
      }

      return { committed: true, pushed, prUrl, branch: activeBranch, filesChanged: commitResult.filesChanged };
    }

    if (autoPush) {
      // worktree 모드에서는 overrideBranch 사용
      if (overrideBranch) activeBranch = overrideBranch;

      const commitResult = commitTaskResult(workdir, taskTitle, agentName);
      if (!commitResult.committed) {
        return { committed: false, pushed: false, prUrl: null, branch: activeBranch, filesChanged: 0 };
      }

      pushed = pushBranch(workdir, activeBranch);
      return { committed: true, pushed, prUrl: null, branch: activeBranch, filesChanged: commitResult.filesChanged };
    }

    // Commit only (local)
    const commitResult = commitTaskResult(workdir, taskTitle, agentName);
    return {
      committed: commitResult.committed,
      pushed: false,
      prUrl: null,
      branch: activeBranch,
      filesChanged: commitResult.filesChanged,
    };
  } catch (err: any) {
    log.error(`Git workflow failed for task "${taskTitle}"`, err);
    return {
      committed: false,
      pushed: false,
      prUrl: null,
      branch: activeBranch,
      filesChanged: 0,
      error: err.message,
    };
  }
}
