import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { createAgentBranch } from "./github.js";
import { createLogger } from "../../utils/logger.js";

const log = createLogger("git-workflow");

// ─── Low-level helper ──────────────────────────────────

/**
 * Execute a git command synchronously.
 * Throws on non-zero exit code.
 */
function gitExec(cwd: string, args: string[]): { stdout: string; stderr: string } {
  const result = spawnSync("git", args, {
    cwd,
    stdio: "pipe",
    timeout: 30000,
    encoding: "utf-8",
  });

  // git binary not found
  if (result.error) {
    const code = (result.error as NodeJS.ErrnoException).code;
    if (code === "ENOENT") {
      throw new Error("git is not installed or not in PATH");
    }
    throw new Error(`git ${args[0]} spawn error: ${result.error.message}`);
  }

  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";

  if (result.status !== 0) {
    throw new Error(`git ${args[0]} failed: ${stderr.trim() || stdout.trim()}`);
  }

  return { stdout, stderr };
}

// ─── Branch detection ──────────────────────────────────

/**
 * Detect the default branch of a git repository.
 * Checks remote HEAD first, then falls back to checking local branches.
 * Returns "main" if detection fails.
 */
export function getDefaultBranch(workdir: string): string {
  // 1. Try remote HEAD (most reliable)
  try {
    const { stdout } = gitExec(workdir, ["symbolic-ref", "refs/remotes/origin/HEAD"]);
    const match = stdout.trim().match(/refs\/remotes\/origin\/(.+)/);
    if (match) return match[1];
  } catch { /* no remote or no HEAD */ }

  // 2. Check if "main" or "master" exists locally
  try {
    const { stdout } = gitExec(workdir, ["branch", "--list", "main", "master"]);
    const branches = stdout.split("\n").map(b => b.replace(/^\*?\s*/, "").trim()).filter(Boolean);
    if (branches.includes("main")) return "main";
    if (branches.includes("master")) return "master";
  } catch { /* no branches */ }

  // 3. Fallback — check current branch (for repos where HEAD is on a non-standard default)
  try {
    const { stdout } = gitExec(workdir, ["rev-parse", "--abbrev-ref", "HEAD"]);
    const branch = stdout.trim();
    if (branch && !branch.startsWith("agent/")) return branch;
  } catch { /* empty repo */ }

  return "main";
}

// ─── Public API ────────────────────────────────────────

/**
 * Stage all changes and create a commit.
 * Returns { committed: false } when there are no staged changes.
 */
export function commitTaskResult(
  workdir: string,
  taskTitle: string,
  agentName: string,
): { committed: boolean; filesChanged: number } {
  // Detect changes (use gitExec to catch .git missing / git not installed)
  const { stdout: statusOutput } = gitExec(workdir, ["status", "--porcelain"]);
  if (!statusOutput.trim()) {
    log.info("No changes to commit");
    return { committed: false, filesChanged: 0 };
  }

  const filesChanged = statusOutput.trim().split("\n").filter(Boolean).length;

  // Warn if no .gitignore — risk of committing secrets/node_modules
  if (!existsSync(join(workdir, ".gitignore"))) {
    log.warn(`No .gitignore found in ${workdir} — git add -A may stage unwanted files`);
  }

  // Stage all changes
  gitExec(workdir, ["add", "-A"]);

  // Commit — title은 단일 행으로 sanitize
  const safeTitle = taskTitle.replace(/[\r\n]+/g, " ").slice(0, 72);
  const safeAgent = agentName.replace(/[\r\n]+/g, " ").slice(0, 50);
  const message = `feat(nova-agent): ${safeTitle}\n\nAgent: ${safeAgent}\nGenerated by Nova Orbit`;
  gitExec(workdir, ["commit", "-m", message]);

  log.info(`Committed ${filesChanged} file(s): ${taskTitle}`);
  return { committed: true, filesChanged };
}

/**
 * Push the given branch to origin.
 * Returns false (logs only) on failure — never throws.
 */
export function pushBranch(workdir: string, branch: string): boolean {
  try {
    gitExec(workdir, ["push", "-u", "origin", branch]);
    log.info(`Pushed branch: ${branch}`);
    return true;
  } catch (err: any) {
    log.warn(`push failed: ${err.message}`);
    return false;
  }
}

/**
 * Merge a branch into the target branch at the project root (not worktree).
 * Used by main_direct mode: worktree branch → main merge.
 */
export function mergeBranch(projectWorkdir: string, sourceBranch: string, targetBranch: string): boolean {
  try {
    gitExec(projectWorkdir, ["checkout", targetBranch]);
    gitExec(projectWorkdir, ["merge", sourceBranch, "--no-ff", "-m", `Merge ${sourceBranch} into ${targetBranch}`]);
    log.info(`Merged ${sourceBranch} → ${targetBranch}`);
    return true;
  } catch (err: any) {
    log.error(`Merge failed (${sourceBranch} → ${targetBranch}): ${err.message}`);
    // Abort merge if in conflict state
    try { gitExec(projectWorkdir, ["merge", "--abort"]); } catch { /* no merge to abort */ }
    try { gitExec(projectWorkdir, ["checkout", targetBranch]); } catch { /* best effort */ }
    return false;
  }
}

/**
 * Sequential merge — 동시 merge 호출 시 큐잉하여 순서대로 실행.
 * git checkout + merge는 atomic하지 않으므로 동시 실행 시 깨질 수 있음.
 * Node.js 단일 프로세스이므로 모듈 레벨 Promise chain이면 충분.
 */
let mergeLock: Promise<void> = Promise.resolve();

export function mergeBranchSequential(
  projectWorkdir: string,
  sourceBranch: string,
  targetBranch: string,
): Promise<boolean> {
  return new Promise((resolve) => {
    mergeLock = mergeLock
      .then(() => {
        resolve(mergeBranch(projectWorkdir, sourceBranch, targetBranch));
      })
      .catch(() => {
        resolve(false);
      });
  });
}

/**
 * Create a pull request via the gh CLI.
 * Returns the PR URL on success, null on failure.
 */
export function createPR(
  workdir: string,
  branch: string,
  title: string,
  body: string,
): string | null {
  const result = spawnSync(
    "gh",
    ["pr", "create", "--head", branch, "--title", title, "--body", body],
    { cwd: workdir, stdio: "pipe", timeout: 30000, encoding: "utf-8" },
  );

  if (result.status === 0) {
    const url = result.stdout?.toString().trim();
    log.info(`PR created: ${url}`);
    return url || null;
  }

  log.warn(`gh pr create failed: ${result.stderr?.toString().trim()}`);
  return null;
}

// ─── High-level workflow ───────────────────────────────

export interface GitWorkflowResult {
  committed: boolean;
  pushed: boolean;
  prUrl: string | null;
  branch: string;
  filesChanged: number;
  error?: string;
}

export type GitMode = "branch_only" | "pr" | "main_direct" | "local_only";

export interface GitHubConfig {
  repoUrl: string;
  branch: string;
  autoPush: boolean;
  prMode: boolean;
  gitMode?: GitMode;
}

export interface GitWorkflowOptions {
  /** worktree 모드에서 이미 생성된 branch 이름. 설정 시 createAgentBranch를 skip한다. */
  overrideBranch?: string;
}

/**
 * Resolve the effective git mode from config.
 * gitMode takes precedence; legacy autoPush/prMode for backward compat.
 */
function resolveGitMode(config: GitHubConfig): GitMode {
  if (config.gitMode) return config.gitMode;
  if (config.prMode) return "pr";
  if (config.autoPush) return "main_direct";
  return "branch_only";
}

/**
 * Execute the full git workflow after a task passes verification.
 *
 * Modes:
 *   local_only    → commit only, no push (로컬 프로젝트 기본값)
 *   branch_only   → agent branch에 commit (push 안함)
 *   pr            → agent branch → push → PR 생성
 *   main_direct   → main에 직접 commit → push (Solo founder 워크플로우)
 */
export function executeGitWorkflow(
  workdir: string,
  taskTitle: string,
  agentName: string,
  githubConfig: GitHubConfig,
  options: GitWorkflowOptions = {},
): GitWorkflowResult {
  const mode = resolveGitMode(githubConfig);
  const { branch: baseBranch } = githubConfig;
  const { overrideBranch } = options;

  let activeBranch = overrideBranch ?? baseBranch;
  let pushed = false;
  let prUrl: string | null = null;

  try {
    if (mode === "local_only") {
      // 로컬 commit만 — push 안함
      const commitResult = commitTaskResult(workdir, taskTitle, agentName);
      return {
        committed: commitResult.committed, pushed: false, prUrl: null,
        branch: activeBranch, filesChanged: commitResult.filesChanged,
      };
    }

    if (mode === "branch_only") {
      // agent branch에 commit — push 안함
      if (!overrideBranch) {
        activeBranch = createAgentBranch(workdir, agentName, taskTitle);
      }
      const commitResult = commitTaskResult(workdir, taskTitle, agentName);
      return {
        committed: commitResult.committed, pushed: false, prUrl: null,
        branch: activeBranch, filesChanged: commitResult.filesChanged,
      };
    }

    if (mode === "pr") {
      // agent branch → commit → push → PR
      if (!overrideBranch) {
        activeBranch = createAgentBranch(workdir, agentName, taskTitle);
      }
      const commitResult = commitTaskResult(workdir, taskTitle, agentName);
      if (!commitResult.committed) {
        return { committed: false, pushed: false, prUrl: null, branch: activeBranch, filesChanged: 0 };
      }
      pushed = pushBranch(workdir, activeBranch);
      if (pushed) {
        const prBody = `Automated task implementation by Nova Orbit agent.\n\nTask: ${taskTitle}\nAgent: ${agentName}`;
        prUrl = createPR(workdir, activeBranch, taskTitle, prBody);
      }
      return { committed: true, pushed, prUrl, branch: activeBranch, filesChanged: commitResult.filesChanged };
    }

    if (mode === "main_direct") {
      // main에 직접 commit → push (Solo founder 워크플로우)
      // worktree 모드에서는 worktree branch에서 commit 후 main으로 merge
      if (overrideBranch && overrideBranch !== baseBranch) {
        // worktree branch에서 commit
        const commitResult = commitTaskResult(workdir, taskTitle, agentName);
        if (!commitResult.committed) {
          return { committed: false, pushed: false, prUrl: null, branch: baseBranch, filesChanged: 0 };
        }
        // main으로 merge는 worktree 정리 후 engine에서 처리
        // 여기서는 commit + push만
        pushed = pushBranch(workdir, overrideBranch);
        return { committed: true, pushed, prUrl: null, branch: overrideBranch, filesChanged: commitResult.filesChanged };
      }
      // 직접 main에서 작업 (worktree 없음)
      const commitResult = commitTaskResult(workdir, taskTitle, agentName);
      if (!commitResult.committed) {
        return { committed: false, pushed: false, prUrl: null, branch: baseBranch, filesChanged: 0 };
      }
      pushed = pushBranch(workdir, baseBranch);
      return { committed: true, pushed, prUrl: null, branch: baseBranch, filesChanged: commitResult.filesChanged };
    }

    // fallback — local_only
    const commitResult = commitTaskResult(workdir, taskTitle, agentName);
    return {
      committed: commitResult.committed, pushed: false, prUrl: null,
      branch: activeBranch, filesChanged: commitResult.filesChanged,
    };
  } catch (err: any) {
    log.error(`Git workflow failed for task "${taskTitle}"`, err);
    return {
      committed: false,
      pushed: false,
      prUrl: null,
      branch: activeBranch,
      filesChanged: 0,
      error: err.message,
    };
  }
}
